"""initial_schema

Revision ID: 6c1890fbeadb
Revises:
Create Date: 2025-10-03 18:26:29.967140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c1890fbeadb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum("VIDEO", "IMAGE", "AUDIO", "MUSIC", "SOUND_EFFECT", name="assettype"),
            nullable=False,
        ),
        sa.Column("source_platform", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("codec", sa.String(length=50), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column(
            "license_type",
            sa.Enum(
                "CC0",
                "CC_BY",
                "CC_BY_SA",
                "PEXELS",
                "PIXABAY",
                "UNSPLASH",
                "CUSTOM",
                name="licensetype",
            ),
            nullable=False,
        ),
        sa.Column("attribution_required", sa.Boolean(), nullable=True),
        sa.Column("attribution_text", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_url", sa.String(length=500), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("perceptual_hash", sa.String(length=64), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column("original_asset_id", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("emotion_tags", sa.JSON(), nullable=True),
        sa.Column("theme_tags", sa.JSON(), nullable=True),
        sa.Column("color_palette", sa.JSON(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("avg_video_views", sa.Float(), nullable=True),
        sa.Column("avg_engagement_rate", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("download_failed", sa.Boolean(), nullable=True),
        sa.Column("asset_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_asset_performance", "assets", ["avg_video_views", "avg_engagement_rate"], unique=False
    )
    op.create_index("idx_asset_source_id", "assets", ["source_platform", "source_id"], unique=False)
    op.create_index(
        "idx_asset_type_quality", "assets", ["asset_type", "quality_score"], unique=False
    )
    op.create_index(op.f("ix_assets_asset_type"), "assets", ["asset_type"], unique=False)
    op.create_index(op.f("ix_assets_created_at"), "assets", ["created_at"], unique=False)
    op.create_index(op.f("ix_assets_perceptual_hash"), "assets", ["perceptual_hash"], unique=False)
    op.create_index(op.f("ix_assets_quality_score"), "assets", ["quality_score"], unique=False)
    op.create_index(op.f("ix_assets_source_platform"), "assets", ["source_platform"], unique=False)
    op.create_table(
        "platforms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "YOUTUBE",
                "TIKTOK",
                "INSTAGRAM",
                "YOUTUBE_SHORTS",
                "LINKEDIN",
                "TWITTER",
                "PINTEREST",
                "SNAPCHAT",
                name="platformname",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("is_configured", sa.Boolean(), nullable=True),
        sa.Column("api_version", sa.String(length=20), nullable=True),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column("default_config", sa.JSON(), nullable=True),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=True),
        sa.Column("max_video_size_mb", sa.Integer(), nullable=True),
        sa.Column("supported_formats", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_publish_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("niche", sa.String(length=100), nullable=True),
        sa.Column("style", sa.String(length=100), nullable=True),
        sa.Column("target_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("actual_word_count", sa.Integer(), nullable=True),
        sa.Column("generator_model", sa.String(length=100), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("prompt_used", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("performance_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scripts_created_at"), "scripts", ["created_at"], unique=False)
    op.create_index(op.f("ix_scripts_niche"), "scripts", ["niche"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_config_user_key", "configurations", ["user_id", "config_key"], unique=True)
    op.create_index(op.f("ix_configurations_user_id"), "configurations", ["user_id"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("niche", sa.String(length=100), nullable=True),
        sa.Column("style", sa.String(length=100), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("fps", sa.Integer(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=10), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "GENERATING",
                "RENDERING",
                "COMPLETED",
                "FAILED",
                "ARCHIVED",
                name="videostatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("generation_time_seconds", sa.Float(), nullable=True),
        sa.Column("ai_model_used", sa.String(length=100), nullable=True),
        sa.Column("tts_model_used", sa.String(length=100), nullable=True),
        sa.Column("total_views", sa.BigInteger(), nullable=True),
        sa.Column("total_likes", sa.Integer(), nullable=True),
        sa.Column("total_comments", sa.Integer(), nullable=True),
        sa.Column("total_shares", sa.Integer(), nullable=True),
        sa.Column("estimated_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("video_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_video_niche_status", "videos", ["niche", "status"], unique=False)
    op.create_index("idx_video_user_created", "videos", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_videos_created_at"), "videos", ["created_at"], unique=False)
    op.create_index(op.f("ix_videos_niche"), "videos", ["niche"], unique=False)
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    op.create_index(op.f("ix_videos_user_id"), "videos", ["user_id"], unique=False)
    op.create_table(
        "analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.BigInteger(), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.Column("dislikes", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("watch_time_minutes", sa.Float(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("avg_view_duration_seconds", sa.Float(), nullable=True),
        sa.Column("avg_view_percentage", sa.Float(), nullable=True),
        sa.Column("ad_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("affiliate_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("unique_viewers", sa.Integer(), nullable=True),
        sa.Column("subscriber_growth", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_analytics_platform_recorded", "analytics", ["platform_id", "recorded_at"], unique=False
    )
    op.create_index(
        "idx_analytics_video_recorded", "analytics", ["video_id", "recorded_at"], unique=False
    )
    op.create_index(op.f("ix_analytics_platform_id"), "analytics", ["platform_id"], unique=False)
    op.create_index(op.f("ix_analytics_recorded_at"), "analytics", ["recorded_at"], unique=False)
    op.create_index(op.f("ix_analytics_video_id"), "analytics", ["video_id"], unique=False)
    op.create_table(
        "publishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("platform_video_id", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "UPLOADING", "PUBLISHED", "FAILED", "DELETED", name="publishstatus"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("platform_metadata", sa.JSON(), nullable=True),
        sa.Column("views", sa.BigInteger(), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_publish_platform_video",
        "publishes",
        ["platform_id", "platform_video_id"],
        unique=False,
    )
    op.create_index(
        "idx_publish_status_scheduled", "publishes", ["status", "scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_publishes_platform_id"), "publishes", ["platform_id"], unique=False)
    op.create_index(
        op.f("ix_publishes_platform_video_id"), "publishes", ["platform_video_id"], unique=False
    )
    op.create_index(op.f("ix_publishes_scheduled_at"), "publishes", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_publishes_status"), "publishes", ["status"], unique=False)
    op.create_index(op.f("ix_publishes_video_id"), "publishes", ["video_id"], unique=False)
    op.create_table(
        "revenue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("platform_id", sa.Integer(), nullable=True),
        sa.Column("revenue_type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("conversion_id", sa.String(length=255), nullable=True),
        sa.Column("revenue_metadata", sa.JSON(), nullable=True),
        sa.Column("earned_at", sa.DateTime(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_revenue_type_earned", "revenue", ["revenue_type", "earned_at"], unique=False
    )
    op.create_index("idx_revenue_video_earned", "revenue", ["video_id", "earned_at"], unique=False)
    op.create_index(op.f("ix_revenue_earned_at"), "revenue", ["earned_at"], unique=False)
    op.create_index(op.f("ix_revenue_platform_id"), "revenue", ["platform_id"], unique=False)
    op.create_index(op.f("ix_revenue_video_id"), "revenue", ["video_id"], unique=False)
    op.create_table(
        "video_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("start_time_seconds", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("effects", sa.JSON(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_video_asset_order", "video_assets", ["video_id", "order_index"], unique=False
    )
    op.create_index(op.f("ix_video_assets_asset_id"), "video_assets", ["asset_id"], unique=False)
    op.create_index(op.f("ix_video_assets_video_id"), "video_assets", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_assets_video_id"), table_name="video_assets")
    op.drop_index(op.f("ix_video_assets_asset_id"), table_name="video_assets")
    op.drop_index("idx_video_asset_order", table_name="video_assets")
    op.drop_table("video_assets")
    op.drop_index(op.f("ix_revenue_video_id"), table_name="revenue")
    op.drop_index(op.f("ix_revenue_platform_id"), table_name="revenue")
    op.drop_index(op.f("ix_revenue_earned_at"), table_name="revenue")
    op.drop_index("idx_revenue_video_earned", table_name="revenue")
    op.drop_index("idx_revenue_type_earned", table_name="revenue")
    op.drop_table("revenue")
    op.drop_index(op.f("ix_publishes_video_id"), table_name="publishes")
    op.drop_index(op.f("ix_publishes_status"), table_name="publishes")
    op.drop_index(op.f("ix_publishes_scheduled_at"), table_name="publishes")
    op.drop_index(op.f("ix_publishes_platform_video_id"), table_name="publishes")
    op.drop_index(op.f("ix_publishes_platform_id"), table_name="publishes")
    op.drop_index("idx_publish_status_scheduled", table_name="publishes")
    op.drop_index("idx_publish_platform_video", table_name="publishes")
    op.drop_table("publishes")
    op.drop_index(op.f("ix_analytics_video_id"), table_name="analytics")
    op.drop_index(op.f("ix_analytics_recorded_at"), table_name="analytics")
    op.drop_index(op.f("ix_analytics_platform_id"), table_name="analytics")
    op.drop_index("idx_analytics_video_recorded", table_name="analytics")
    op.drop_index("idx_analytics_platform_recorded", table_name="analytics")
    op.drop_table("analytics")
    op.drop_index(op.f("ix_videos_user_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_niche"), table_name="videos")
    op.drop_index(op.f("ix_videos_created_at"), table_name="videos")
    op.drop_index("idx_video_user_created", table_name="videos")
    op.drop_index("idx_video_niche_status", table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_configurations_user_id"), table_name="configurations")
    op.drop_index("idx_config_user_key", table_name="configurations")
    op.drop_table("configurations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_scripts_niche"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_created_at"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_table("platforms")
    op.drop_index(op.f("ix_assets_source_platform"), table_name="assets")
    op.drop_index(op.f("ix_assets_quality_score"), table_name="assets")
    op.drop_index(op.f("ix_assets_perceptual_hash"), table_name="assets")
    op.drop_index(op.f("ix_assets_created_at"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_type"), table_name="assets")
    op.drop_index("idx_asset_type_quality", table_name="assets")
    op.drop_index("idx_asset_source_id", table_name="assets")
    op.drop_index("idx_asset_performance", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
